### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [AlexanderKuptsov/InterpreterTinyBasic#1]
1. Нужна автоматическая сборка с помощью `make`, а не `cmake`.
2. Приведите в порядок свой code style (snake case vs camel case)
3. Хотелось бы избавиться от глобальных переменных, инкапсулировав состояние интерпретатора/парсера в структуры, а всё что можно убрав просто в локальные переменные.
5. Стек тоже можно сделать расширяющимся, ну или хотя бы настраиваемым извне. Для демонстрации работы со стеком было бы здорово добавить пример с рекурсией, например, факториал.
6. Можно попробовать токен тоже не ограничивать 80 символами.
7. `mem.h` лучше заменить на стандартный `string.h`

**Comment by AlexanderKuptsov** [comment]
Исправил замечания

**Comment by gagarski** [comment]
1. Пока не вижу Makefile
2. Не вижу ни одного вызова `free`, но вижу вызовы `malloc`. Всю динамически выделенную память нужно освобождать. Утилита `valgrind` поможет найти утечки.
3. На IfTest на одном из компьютеров падает в этом месте:
<img src="https://i.imgur.com/w2snIpT.png"/>
Какой-то плавающий баг, похоже. Попробуйте поотлаживать/поvalgrindить.
4. Глобальные переменные всё ещё на месте.
